# Generated by Django 5.2.6 on 2025-09-25 00:39

import django.db.models.deletion
from django.db import migrations, models

def create_default_status(apps, schema_editor):
    Status = apps.get_model('posts', 'Status')
    # Create a default status if it doesn't exist
    Status.objects.update_or_create(
        id=1,
        defaults={'name': 'Draft', 'description': 'Default status for posts.'}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20250922_2148'),
    ]

    operations = [
        # First, create the default Status row
        migrations.RunPython(create_default_status),
        
        # Then add the ForeignKey field
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='posts.status'
            ),
            preserve_default=False,
        ),
    ]
